/**
 * @file assets.ts
 * @description Comprehensive list of assets to monitor for financial calls.
 * Includes Top 100 Crypto and Top 50 Stocks/Indices.
 */

export const MONITORED_ASSETS: string[] = [
    // --- TOP CRYPTO (Names & Tickers) ---
    'bitcoin', 'btc', 'satoshi',
    'ethereum', 'eth', 'ether', 'vitalik',
    'solana', 'sol',
    'cardano', 'ada',
    'xrp', 'ripple',
    'dogecoin', 'doge', 'dogecoin',
    'shiba', 'shib', 'shiba inu',
    'polkadot', 'dot',
    'avalanche', 'avax',
    'chainlink', 'link',
    'polygon', 'matic',
    'litecoin', 'ltc',
    'uniswap', 'uni',
    'cosmos', 'atom',
    'stellar', 'xlm',
    'monero', 'xmr',
    'algorand', 'algo',
    'near', 'near protocol',
    'aptos', 'apt',
    'sui',
    'arbitrum', 'arb',
    'optimism', 'op',
    'pepe',
    'bonk',
    'wif', 'dogwifhat',
    'render', 'rndr',
    'fetch', 'fet',
    'injective', 'inj',
    'celestia', 'tia',
    'sei',
    'ondo',
    'pyth',
    'jito', 'jto',
    'aave',
    'maker', 'mkr',
    'curve', 'crv',
    'lido', 'ldo',
    'thorchain', 'rune',
    'fantom', 'ftm',
    'ton', 'toncoin',
    'kaspa', 'kas',
    'chiliz', 'chz',
    'zcash', 'zec',
    'bittensor', 'tao',
    'stacks', 'stx',
    'immutable', 'imx',
    'cronos', 'cro',
    'hedera', 'hbar',
    'filecoin', 'fil',
    'internet computer', 'icp',
    'vechain', 'vet',
    'quant', 'qnt',
    'the graph', 'grt',
    'eos',
    'elrond', 'egld',
    'flow',
    'tezos', 'xtz',
    'axie', 'axs',
    'sandbox', 'sand',
    'decentraland', 'mana',
    'theta',
    'neo',
    'klaytn', 'klay',
    'bitcoin cash', 'bch',
    'etc', 'ethereum classic',
    'tron', 'trx',

    // --- TOP STOCKS (Names & Tickers) ---
    // Tech / MAG7
    'apple', 'aapl',
    'microsoft', 'msft',
    'nvidia', 'nvda',
    'google', 'goog', 'googl', 'alphabet',
    'amazon', 'amzn',
    'meta', 'facebook',
    'tesla', 'tsla',
    'netflix', 'nflx',

    // Semiconductors / AI
    'amd',
    'intel', 'intc',
    'tsmc', 'tsm',
    'broadcom', 'avgo',
    'micron', 'mu',
    'qualcomm', 'qcom',
    'arm',
    'super micro', 'smci',
    'palantir', 'pltr',

    // Crypto Proxies
    'coinbase', 'coin',
    'microstrategy', 'mstr', 'saylor',
    'marathon', 'mara',
    'riot',
    'cleanspark', 'clsk',
    'hut8', 'hut',
    'robinhood', 'hood',
    'block', 'sq',
    'paypal', 'pypl',

    // Meme / Retail
    'gamestop', 'gme',
    'amc',
    'reddit', 'rddt',

    // Financials
    'jpmorgan', 'jpm',
    'goldman sachs', 'gs',
    'visa', 'v',
    'mastercard', 'ma',
    'blackrock', 'blk',

    // Auto / Industry
    'ford', 'f',
    'gm', 'general motors',
    'rivian', 'rivn',
    'lucid', 'lcid',
    'boeing', 'ba',

    // Energy
    'exxon', 'xom',
    'chevron', 'cvx',
    'uranium', 'urnm', 'ccj',

    // --- INDICES / ETFs ---
    'spy', 'spx', 's&p', 's&p 500',
    'qqq', 'nasdaq', 'ndx',
    'dow', 'dia', 'dji',
    'russell', 'iwm', 'rut',
    'vix',
    'gold', 'gld',
    'silver', 'slv',
    'oil', 'uso',
    'tlt', 'bonds', 'treasuries',
    'dxy', 'dollar',
];
